version: "3"

services:
  app:
    container_name: flask-app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
#    expose:
#      - "5000"
#    volumes:
#      - app-data:/usr/src/app/static
#    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
#    volumes:
#      - .:/www/static
#      - app-data:/usr/src/app/static
    links:
      - app:app

  ejabberd:
    container_name: ejabberd
    build:
      context: ./ejabberd
      dockerfile: Dockerfile
    restart: always
    volumes:
      - './ejabberd/templates/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml'
    ports:
      - 5222:5222
      - 5280:5280

networks:
  arjanet:
