---
## Install containers with docker-compose
#
- name: Run docker-compose for ARJA-stack
  docker_compose:
    project_name: arja-stack
    project_src: ./roles/docker/compose/
    state: present # Specifying present is the same as running docker-compose up
