# Set base image (host OS)
FROM ejabberd/ecs:latest
#FROM rroemhild/ejabberd:latest

# Set one or more individual labels
LABEL version="0.0.1-beta"
LABEL author="muutttu@live.fi"

#ADD ./templates/ejabberd.yml.tpl /opt/ejabberd/conf/ejabberd.yml.tpl
#ADD ./templates/ejabberdctl.cfg.tpl /opt/ejabberd/conf/ejabberdctl.cfg.tpl
#ADD ./templates/example.com.pem /opt/ejabberd/ssl/example.com.pem