---
# tasks file for docker host system

# Installs Docker SDK
# --
# Installing Docker SDK by from PIP
- name: Install Docker SDK library for Python
  pip:
    name:
      - docker
      - docker-compose
      # docker-py # Python module has been superseded by docker
    state: present
