---
# tasks file for docker host system

# Installs Docker SDK
# --
# Installing Docker SDK by from PIP
- name: Install Docker SDK library for Python
  pip:
    name:
      - docker
      - docker-compose
      # docker-py # Python module has been superseded by docker
    state: present


# Install as per https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04
- name: Add Docker GPG apt Key
  become: true # Apply shell command as 'root'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository for Ubuntu 20.04 Focal
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker-CE
  become: true
  apt:
    name:
    - docker-ce
    - python3-docker
    #- docker-ce-cli
    #- containerd.io
    state: latest
    update_cache: true


- name: Upgrade Docker SDK library for Python
  become: true
  pip:
    name:
      - docker
      #- docker-compose
      # docker-py # Python module has been superseded by docker
    #state: present
    extra_args: --upgrade

# Create docker group
#- name: create docker group
#  command: sudo groupadd docker

- name: Add user to docker group
  become: true
  user:
    name: "{{ansible_user}}"
    group: docker

- name: Download docker-compose {{ docker_compose_version }}
  get_url:
    url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: ~/docker-compose
    mode: '+x'

#- name: Check docker-compose exists
#  stat:
#    path: ~/docker-compose
#  register: docker_compose

#- name: Move folder docker-compose to /usr/local/bin/
#  become: true # Apply shell command as 'root'
#  shell: mv ./docker-compose /usr/local/bin/docker-compose
#  when: docker_compose.stat.exists

- name: Install Docker-compose
  become: true
  #  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
    dest: /usr/local/bin/docker-compose
    mode: +x