---
# Install service arja-stack with docker-compose
#
# Install test service stack with docker-compose
#
- name: Docker-compose | Copy docker-compose folder and files
  copy:
    src: ./roles/docker/files/compose
    dest: "{{ docker_host_home_folder }}" # Tämä tulee vars/main.yml:stä
    #owner: foo
    #group: foo
    mode: 0644

- name: Docker-compose | Build images and run containers for ARJA-stack (takes a long time...)
  community.docker.docker_compose:
    project_name: arja
    project_src: "{{ docker_host_home_folder }}/compose"
    #docker_host: "tcp://{{ docker_host_ip }}:2375" # Local socket, kun docker context
    files:
      - docker-compose.yml
    state: present # Specifying present is the same as running docker-compose up
