# tasks file for docker host system
---
# Remove pre-installed Docker system services
- name: Docker-host | Remove pre-installed packages
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

# Add Docker GPG Key
- name: Docker-host | Add Docker GPG APT key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add Docker Ubuntu 20 (Focal) repo
- name: Docker-host | Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

# Install Docker-CE
- name: Docker-host | Install Docker Community Edition
  apt:
    name: docker-ce
    state: latest

# Install Docker python SDK from PIP
- name: Docker-host | Install Docker and Compose SDKs for Python
  pip:
    name:
      - docker
      - docker-compose
    state: present

# Upgrade Docker python SDK just in case
- name: Docker-host | Upgrade Docker SDK library for Python
  pip:
    name:
      - docker
    extra_args: --upgrade