---
# tasks file for docker host system

# Installs Docker SDK
# --
#
- name: Install python Docker SDK library
  pip:
    name:
      - docker
      - docker-compose
    state: present



# docker-compose:
- name: Run docker-compose for ARJA-stack
  docker_compose:
    project_name: arja-stack
    project_src: ./roles/docker/compose/
    state: present # Specifying present is the same as running docker-compose up
