---
## Prepare the Ubuntu servers
- name: Setup Docker and services
  hosts:
    - demogroup
    #- ubuntu
  become: true  # All shell commands as 'root'
  tasks:
    - import_role:
        name: docker
      tags: docker
