# main.yml
---
# master playbook for the project
## Connectivity testing play:
- name: Connectivity tests
  import_playbook: testssh.yml

## Bootstrapping with package and library update
- name: Bootstrapping
  import_playbook: bootstrap.yml

## Deploy Docker container stack
- name: Docker services
  import_playbook: docker.yml
