# main.yml
---
- name: "Deploy ARJA comms stack"
  hosts: locals
  connection: local
  roles:
    - bootstrap # Prepare the host system
    - docker-host # Prepare docker host
    - docker-containers # Install Docker container services